[package]
name = "ohes"
version = "0.1.0"
edition = "2021"

[dependencies]
limine = "0.1.11"
buddy_system_allocator = "0.9.0"
klogger = "0.0.16"
spin = "0.9.8"
font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }